# Generated by Django 3.2.5 on 2021-07-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
